import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from '@/components/header/header';
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import AuthProvider from '@/context/AuthProvider';
import { cookies } from 'next/headers';
import '../globals.css';
import Footer from '@/components/footer/footer';
import BackToTop from '@/components/backtotop/BackToTop';
import Contact from '@/components/contact/Contact';
import Phone from '@/components/phone/Phone';
import Provider from '@/utils/Provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const cookieStore = cookies();
	const sessionToken = cookieStore.get('sessionToken');
	return (
		<html lang='en'>
			<body className={inter.className}>
				<AuthProvider initialSessionToken={sessionToken?.value}>
					<Provider>
						<Header />
						{children}
						<Footer />
						<Contact />
						<Phone />
					</Provider>
					<BackToTop />
				</AuthProvider>
				<ToastContainer />
			</body>
		</html>
	);
}
